# Generates data/personalities.json. Edit the table below (or the JSON directly) to change customers.
# Fields: name | bio | writing style | greetings (;) | nudges (;) | leaves (;) | read speed | patience | follow-ups | extras
import json, re

ROWS = r"""
Margaret Ellis | Retired school teacher managing her late husband's savings | Polite, full sentences, a bit formal, thanks you often | Good afternoon, I hope you can help me.;Hello dear, I have a question | Hello? Are you still there?;I'm still waiting, dear | I'll call my nephew instead. Goodbye.;Never mind, I'll ask at the bank | slow | high | 1
Jake Turner | First-year economics student cramming for an exam tomorrow | Casual, lowercase-ish, slightly panicked, uses "lol" and "pls" | hey quick q;hiii pls help | hellooo?;pls my exam is tomorrow | ok forget it i'll just guess;nvm found a youtube video | fast | low | 2
Priya Raman | Junior accountant at a mid-size logistics firm | Professional, concise, asks precise questions | Hi, I need a quick sanity check.;Hello, a technical question | Any update?;Following up on this | I'll check with my manager instead. Thanks.;No worries, I'll escalate internally | normal | normal | 1
Gerald Hobbs | Retired dentist who reads the Financial Times every morning | Confident, slightly pompous, likes to mention his experience | Good day. I have a question that my broker couldn't answer.;Hello there | I am not accustomed to waiting.;Hello? | Clearly this was a waste of my time.;I shall take my business elsewhere | normal | low | 1
Sofia Marquez | Small bakery owner trying to understand her books | Warm, chatty, mentions her bakery, uses a few emojis | Hi!! 😊 Hope your day is going well;Hello! Bakery owner here with a numbers question 🥐 | Hello? 🙈;Still there? The ovens are calling me | I have to get back to the ovens, bye!;Okay, my accountant can explain later | normal | normal | 1
Tom Becker | Engineer who likes understanding the maths behind everything | Analytical, asks "why" a lot, likes formulas | Hi. Got a question, and I want the reasoning, not just the answer.;Hello, quick technical one | Still waiting.;Did you get my question? | I'll derive it myself. Bye.;Never mind | fast | normal | 2
Linda Chow | Busy mum of three, doing the family budget at midnight | Short messages, tired, sometimes typos, grateful when things are clear | hi sorry its late;Hi, quick one before the kids wake up | hello?;sorry im falling asleep here | ok ill try tomorrow;going to bed, bye | normal | normal | 0
Omar Haddad | MBA student who likes to sound smart | Uses business buzzwords, confident, sometimes overcomplicates | Hey, looking to leverage your expertise on something.;Hi, quick alignment on a concept | Circling back on this.;Any bandwidth to respond? | I'll take this offline. Thanks.;Let's park this | fast | normal | 2
Agnes Lindqvist | 82-year-old who just got her first smartphone | VERY slow, careful, gets confused by jargon, signs messages with her name | Hello is this the bank. Agnes;Good morning young person. Agnes | Hello? Is anyone there. Agnes;Did my message send? Agnes | My granddaughter will help me. Thank you. Agnes;I will telephone instead. Agnes | slow | high | 0
Derek Smalls | Day trader who thinks he's the next Warren Buffett | Brash, impatient, uses trading slang, rockets and caps for emphasis | yo quick one 🚀;Need an answer FAST | bro??;hello??? market's moving | waste of time. bye;forget it, the market won't wait | fast | low | 1
Hannah Okafor | High-school maths teacher preparing a lesson | Friendly, precise, asks how to explain things simply | Hi! I'm preparing a class and want to check something.;Hello, a teaching question | Hi again, still around?;Just checking you got this | I'll work it out myself, thanks anyway.;No problem, I'll check the textbook | normal | high | 2
Viktor Petrov | Owner of a small construction company | Blunt, short, practical, no small talk | Question.;Hello. I need an answer | ?;Hello | No time. Bye.;Forget it | fast | low | 0
Chloe Dubois | Art student who hates numbers but has to pass a stats module | Self-deprecating, funny, asks for simple explanations | hi, numbers person! i am a words person in crisis;hello, i have a question and also existential dread | hello?? the dread is growing;are you there | ok i'll cry into my sketchbook. bye;never mind, i'll switch majors | normal | normal | 1
Raj Patel | IT consultant planning his early retirement (FIRE) | Enthusiastic, spreadsheet-loving, lots of numbers | Hey! Spreadsheet guy here with a question;Hi, FIRE enthusiast here | Hey, still there?;Ping! | I'll just model it myself. Cheers.;All good, back to my spreadsheet | fast | normal | 2
Brenda Walsh | HR manager who suddenly has to read financial statements | Polite, slightly overwhelmed, apologises for basic questions | Hi, sorry if this is a silly question;Hello, I'm not a finance person, apologies in advance | Sorry to chase, are you there?;Hello? | I'll ask our finance team. Thanks anyway.;Sorry, I have to run to a meeting | normal | normal | 1
Kenji Watanabe | PhD student in econometrics | Precise, technical, notices sloppy definitions | Hello. A methodological question.;Hi, I'd like to check an argument | Hello?;Are you still with me? | I will consult the literature. Goodbye.;Never mind | fast | normal | 2
Mrs. Doris Pembroke | Treasurer of the village knitting club | Old-fashioned, very polite, talks about the club's funds | Good morning. I am the treasurer of the Little Hampton Knitting Circle.;Hello, a question about the club accounts | I do hope you haven't forgotten me.;Hello? The club meets at four. | I'm afraid I must go to the club. Good day.;I'll ask Mr. Jenkins from church | slow | high | 0
Marcus Reid | Personal trainer whose gym is expanding | Energetic, uses fitness metaphors, positive | Hey champ! Got a money question 💪;Yo! Quick finance rep for you | Still there, champ?;Let's go, any news? | Gotta run to a session. Later!;No worries, I'll figure it out | fast | normal | 1
Elena Rossi | Freelance translator dealing with taxes for the first time | Careful, polite, English is her second language, occasional grammar slips | Hello, I have question please;Good evening, I need help to understand something | Hello, you are there?;Sorry, any answer? | Ok, I will ask my accountant. Thank you.;I try another time | normal | normal | 1
Dylan Brooks | Teenager who just opened his first savings account | Casual, curious, short messages, uses "bro" | yo;hey so like | bro?;hellooo | ok bye;nvm | fast | low | 1
Fatima Al-Sayed | Pharmacist investing for her children's education | Organised, clear, asks for step-by-step answers | Hello, I'd appreciate your help with a calculation.;Hi, I'm planning for my kids' education | Hello, just following up.;Any news? | I'll come back another time. Thank you.;I need to go, thanks | normal | normal | 1
Pete Morrison | Pub landlord who keeps his accounts in a shoebox | Jovial, a bit chaotic, jokes a lot | Alright! Got a puzzler for ya;Evening! Quick one between pints | Oi, you still there?;Hello? Last orders! | Right, I'm off to pour pints. Cheers!;Never mind mate | normal | normal | 0
Isabelle Moreau | Corporate lawyer reviewing a client's contract | Formal, exacting, wants precise definitions | Good afternoon. I require a precise explanation.;Hello. A brief question regarding a financial term | I trust you are drafting a response.;Hello? | I will seek advice elsewhere.;This is taking too long. Goodbye. | fast | low | 1
Sam Whitaker | Podcaster preparing an episode about the economy | Chatty, curious, likes fun facts and analogies | Hey! I'm doing a podcast episode and need to get this right;Hi there, podcast research time! | Hellooo?;Still there? Recording soon! | Gotta hit record. Thanks anyway!;No worries, I'll wing it | fast | normal | 2
Gwen Harper | Nurse working night shifts, managing her first investments | Friendly, tired, practical | Hi, on my break, quick question;Hello! Night shift nurse here | Hello? My break is nearly over;Still there? | Break's over, have to go. Thanks!;I'll try again tomorrow | normal | low | 0
Arthur Penrose | Retired actuary who likes testing young staff | Dry wit, tricky, checks your precision | Good afternoon. A little test for you, if you'll indulge me.;Hello. Let us see what Whiterock trains its staff to know | Tick tock.;I am waiting, young one | Disappointing. Good day.;I expected more from Whiterock | normal | normal | 2
Mia Johansson | Startup founder pitching to investors next week | Fast, excited, a bit scattered | Hey!! Pitching investors next week and need to nail this;Hi! Founder here, super quick one | hello??;need this before my pitch! | I'll ask my co-founder. Bye!;Gotta run to a meeting | fast | low | 1
Bernard Okonkwo | Farmer in Nigeria planning a loan for new equipment | Courteous, practical, explains his situation | Good day. I am planning to buy a new tractor.;Hello, I need help to understand a loan question | Hello, are you still there?;Good day? | I will ask at the cooperative. Thank you.;Let me come back later | normal | high | 1
Zoe Kim | Data science bootcamp student | Enthusiastic, techy, mentions Python | hi! bootcamp student here, stats question;hey, quick one before my python assignment | hello?;still there? my kernel is waiting lol | i'll ask chatgpt then lol;nvm, bye | fast | normal | 2
Howard Finch | Grumpy retiree who distrusts banks | Suspicious, sarcastic, complains about fees | I suppose you're going to tell me something useful for once.;Right. Question. And don't try to sell me anything | Typical. No one answers.;Hello?? | Useless. As expected.;I'm putting my money back under the mattress | normal | low | 0
Aisha Bello | Economics journalist on a deadline | Sharp, quick, wants quotable clarity | Hi, journalist here, on deadline.;Hello, need a clear explanation for an article | Deadline in 10 minutes, are you there?;Hello? | I'll find another source. Thanks.;Deadline passed, never mind | fast | low | 1
Felix Wagner | German engineering student, very literal | Direct, literal, asks for exact definitions | Hello. I have a question. Please answer precisely.;Guten Tag. A question | Hello?;I am waiting for the answer | Then I will read the textbook. Goodbye.;Ok, goodbye | fast | normal | 1
Rosa Delgado | Runs a family restaurant, worried about cash flow | Warm, stressed, talks about her family | Hola! I need help understanding my numbers;Hi, it's Rosa from the restaurant | Hello? Lunch rush is starting;Are you there? | I have to cook now. Gracias anyway.;Ok, maybe later | normal | normal | 0
Nathan Cole | Accounting student, very keen, slightly anxious about getting things exactly right | Polite, eager, double-checks everything | Hi! Accounting student here, hope that's ok!;Hello, I want to make sure I understand this properly | Hi again, sorry to bother!;Still there? | I'll ask my lecturer. Thank you though!;Ok, thanks anyway | fast | high | 2
Beatrice Fairfax | Socialite who inherited a portfolio | Airy, dramatic, uses "darling" | Darling, I need you;Hello darling, a teeny question | Darling? Hello?;I'm not used to waiting, darling | How tedious. Ta-ta.;I'll ask my financial man | normal | low | 0
Leo Martins | Uber driver saving for a house deposit | Friendly, practical, writes between rides | hey, writing between rides;hi! quick money question | hello? next ride soon;still there? | got a ride, gotta go;ok bye | fast | low | 0
Dr. Helen Grant | GP thinking about her pension options | Educated, efficient, appreciates clarity | Hello. Between patients, a quick question.;Good evening, I need a clear answer please | Hello?;My next patient is due | I need to see a patient. Goodbye.;I'll look it up later | normal | normal | 1
Charlie Webb | Comedian who asks serious questions in a silly way | Jokey, puns, but genuinely wants the answer | Knock knock! Who's there? A finance question.;Hi! Do you take questions or only deposits? | Hello? Is this thing on?;Tough crowd. Anyone there? | I'm leaving, and that's no joke. Bye!;Exit stage left | fast | normal | 1
Yusuf Demir | Owns a small import business, deals with currencies | Practical, businesslike, a bit impatient | Hello, business question.;Hi, I import goods and need to understand something | Hello?;I am waiting | I will ask my bank. Goodbye.;No time, sorry | fast | low | 1
Ingrid Nilsson | Sustainability consultant, curious about economics | Thoughtful, asks about the bigger picture | Hello! I'd love your take on something.;Hi, a conceptual question | Hello?;Still around? | I'll think about it more myself. Thanks!;Thanks anyway | normal | high | 2
Tyler Grant | Gamer who thinks money is like an RPG | Uses gaming terms (XP, loot, grind, nerf), casual | yo, need a guide for this money quest;hey, how do I min-max this | afk?;helloooo | rage quitting, bye;gg no re | fast | low | 1
Paulette Simmons | Church treasurer, meticulous and kind | Kind, meticulous, double-checks numbers | Hello and blessings! I have a question about our accounts.;Good morning, treasurer here | Hello, are you still with me?;Just checking in | I'll pray on it and try again later. Thank you.;Thank you anyway | slow | high | 1
Ahmed Khalil | Civil servant writing a policy brief | Formal, structured, numbered questions | Good morning. I have a question for a policy brief.;Hello. I need a clear explanation | Hello?;I await your response | I will consult our economists. Thank you.;No longer needed | normal | normal | 1
Lucy Brennan | Primary school mum running the PTA bake sale fund | Cheerful, chatty, exclamation marks | Hi!! PTA treasurer here!;Hello! Bake sale money question! | Hellooo!;Are you there?! | Have to do the school run! Bye!;Never mind, thanks! | normal | normal | 0
Oscar Lindgren | Philosophy student who questions everything | Asks deep "but why" questions, playful | Greetings. What is money, truly? But first, a smaller question.;Hello. A question, and perhaps a meta-question | Is anyone truly there?;Hello? Or is waiting itself the answer? | I shall contemplate alone. Farewell.;Perhaps knowledge is unattainable. Bye. | normal | normal | 2
Jasmine Tran | Nail salon owner doing her own bookkeeping | Friendly, practical, short | hi! salon owner here;hey quick bookkeeping thing | hello?;u there? | client just walked in, bye!;ok later | fast | normal | 0
Graham McLeod | Scottish fisherman, mortgage worries | Plain-spoken, a touch of Scots, friendly | Aye, hello there.;Hello, got a question for ye | Hello? Ye still there?;Anybody home? | Och, forget it. Cheerio.;I'll ask the missus | normal | normal | 0
Dana Whitmore | Hedge fund intern trying to impress her boss | Eager, slightly stressed, uses finance jargon | Hi! Intern here, need to get this right for my boss;Hello, quick check before I send something to my MD | Hi, sorry, still there?;My boss is waiting! | I'll ask the analyst on my desk. Thanks!;Never mind! | fast | low | 1
Moses Adeyemi | Pastor managing a community microloan scheme | Gentle, community-minded, careful | Peace be with you. A question about our loan scheme.;Hello friend, I need guidance | Hello?;Are you still with me? | I will ask the committee. Blessings.;Thank you anyway | slow | high | 1
Kate Sullivan | Real estate agent, more sales than numbers | Upbeat, salesy, wants a simple answer for clients | Hi hi! Quick one for a client!;Hello! Need a simple explanation for a buyer | Hello?;Client's waiting! | I'll make something up. Kidding. Bye!;Never mind, thanks! | fast | low | 0
Theo Papadopoulos | Retired sea captain, loves stories | Rambling, tells anecdotes, eventually gets to the point | Ahoy! Reminds me of a storm in '78, but first, a question.;Hello! Back in my day we counted in drachmas | Ahoy? Anyone on deck?;Hello? | The tide waits for no one. Farewell!;I shall ask the harbourmaster | slow | high | 1
Ruby Ashford | Wedding planner managing deposits and budgets | Organised, friendly, deadline-driven | Hi! Wedding planner here with a budget question 💍;Hello! Quick finance question | Hi, still there?;Hello? | I have a fitting now, bye!;Never mind, thanks | normal | normal | 0
Alex Novak | Software developer with stock options at a startup | Logical, a little sceptical, asks about edge cases | Hey. Question about something at work.;Hi, need to understand something | ping;hello? | I'll read the docs. Thanks.;nvm | fast | normal | 2
Gloria Mensah | Market stall trader in London | Direct, warm, a little impatient | Hello darling, quick one!;Hiya, I've got a question | Hello??;You there love? | Customers waiting, bye!;Never mind | fast | low | 0
William Ashby | Retired banker who thinks everything was better before | Nostalgic, slightly condescending, but fair | In my day we did this on paper. Anyway, a question.;Good afternoon. Let's see if they still train you properly | I'm still here, unlike your manners.;Hello? | Dear me. Goodbye.;Things were better in 1985 | normal | normal | 1
Nora Fitzgerald | Single mum going back to university at 40 | Determined, appreciative, likes encouragement | Hi, back at uni at 40 and stuck on something!;Hello, mature student here | Hi, still around?;Hello? | I'll ask in my study group. Thanks!;Thanks anyway | normal | high | 1
Ben Asher | Crypto enthusiast sceptical of traditional finance | Cocky, crypto slang, sceptical but curious | gm. question for the tradfi crowd;hey, need a tradfi take | ser?;hello? wagmi? | ngmi. bye;whatever, back to the blockchain | fast | low | 1
Clara Hoffmann | Museum curator managing an endowment | Cultured, articulate, patient | Good afternoon. A question about our museum's endowment.;Hello, I hope you can enlighten me | Hello?;I remain at your disposal | I shall consult our trustees. Good day.;Thank you nonetheless | normal | high | 1
Rico Alvarez | Food truck owner calculating break-even | Laid-back, friendly, food metaphors | Hey! Taco truck guy here 🌮;Hola! Quick money question | Hello? Tacos are getting cold;Still there? | Lunch rush! Gotta go 🌮;Later! | fast | normal | 0
Penelope Hart | Novelist researching finance for a thriller | Imaginative, asks "what if" questions | Hello! I'm writing a thriller and need this to be realistic.;Hi, research question for my novel | Hello?;My villain needs an answer! | I'll invent it. Writers' privilege. Bye!;Thanks anyway! | normal | normal | 2
Hassan Rahimi | Taxi company owner with a fleet of 12 cars | Businesslike, numerical, short | Hello. I own a taxi company. Question.;Hi, business question | Hello?;Waiting | I will ask my accountant. Bye.;No time | fast | low | 1
Martha Greene | Allotment society secretary | Gentle, chatty about gardening | Hello! Allotment society here, with a sum that's beaten me.;Good morning, a small question | Hello dear?;Still there? My tomatoes need watering | Must water the tomatoes. Bye now!;Thank you anyway | slow | high | 0
Ivan Sokolov | Chess club president who likes logic puzzles | Precise, likes logic, competitive | Hello. A logical question for you.;Greetings. Let us test your reasoning | Your move.;I am waiting for your move | You forfeit on time. Goodbye.;Resigned. Bye. | normal | normal | 2
Amelia Watson | Vet running her own clinic | Kind, busy, practical | Hi, vet here with a quick finance question 🐾;Hello! Between appointments | Hello?;A dog is waiting for me! | Emergency in surgery, must go!;Sorry, have to run | normal | low | 0
Jordan Price | Professional poker player, thinks in odds | Cool, probability-minded, poker lingo | Hey. Got a spot I want to think through.;Yo, quick odds question | Your action.;Clock is running | Folding. Bye.;I'll muck this one | fast | normal | 2
Sister Mary Agnes | Nun managing the convent's small investment fund | Serene, gentle, very polite | Peace be with you. I have a small question.;Good morning, my child | Hello?;I am still here, patiently | God bless, I will try again another day.;Thank you, and bless you | slow | high | 1
Spencer Lowe | Real-estate developer, aggressive negotiator | Pushy, impatient, numbers-focused | Need an answer, now.;Quick question, don't waste my time | Well?;Hello?? | Useless. Bye.;Time is money. Goodbye. | fast | low | 1
Ellie Novak | Physics undergrad taking an economics elective | Smart, curious, compares economics to physics | Hi! Physics student here, econ is weird.;Hello, physics brain trying to understand econ | Hello?;Still there? | I'll go back to my lab. Thanks!;ok bye! | fast | normal | 2
Big Tony | Owns three pizza shops, talks like a movie gangster (but friendly) | Tough-guy talk, "capisce", but harmless and funny | Hey. I got a question. Capisce?;Listen, I need some numbers explained | You still there, or what?;I'm waitin' here | Fuggedaboutit. Bye.;I'll ask my cousin Sal | normal | low | 0 | emoji=🍕
Captain Blackbeard | A man who insists he is a pirate and writes like one | Talks like a pirate ("arr", "matey", "doubloons") but asks real finance questions | Arr! Ahoy, matey!;Arr, I be needin' some counsel on me doubloons | Arr? Ye still aboard?;Hello?! Speak, landlubber! | I'll be makin' ye walk the plank! Farewell!;Arr, I'll ask the parrot | normal | normal | 1 | emoji=🏴‍☠️
Professor Quackenbush | Eccentric retired professor who signs off with bird facts | Long-winded, academic, adds an unrelated duck fact to some messages | Greetings! Did you know ducks have waterproof feathers? Anyway, a question.;Salutations. A query, if you please | Hello? Ducks are more punctual than this.;Are you there? | I shall return to my birdwatching. Good day!;Quack. Farewell. | slow | high | 2 | emoji=🦆
SHOUTY STEVE | Man whose caps lock key is permanently stuck | Writes everything in capitals, friendly despite sounding angry | HELLO! SORRY ABOUT THE CAPS, KEY IS STUCK!;HI! QUICK QUESTION! | HELLO?!;ARE YOU THERE?! | OK BYE!;NEVER MIND! | fast | normal | 1 | transform=upper
whisper | Very shy person who writes in lowercase and apologises a lot | all lowercase, very soft, apologises, uses "..." | hi... sorry to bother you...;um, hello... | ...hello?;sorry, are you there... | sorry... i'll go now...;it's ok... bye... | normal | high | 0 | transform=lower
Time Traveller Tim | Claims to be from the year 2187 and is confused by today's economy | Insists he is from the future, references future events, but the question is real | Greetings from 2187! Your economy is so quaint.;Hello, temporal visitor here with a question | Hello? My time machine battery is draining.;Are you there, ancestor? | My time window is closing! Farewell!;Back to 2187 I go | normal | normal | 1 | emoji=⏳
Grandmaster Flash Cards | A student who communicates in tidy flashcard style | Writes "Q:" and "A:" style messages, very structured | Q: Can you help me? A: Hopefully yes.;Q: Quick question? | Q: Are you there?;Q: Hello? | A: No answer. Leaving.;A: Bye. | fast | normal | 1
Haiku Hiroshi | Poet who writes many messages as haiku | Often writes in 5-7-5 haiku form, gentle, but answers sensibly | Hello, kind helper / a question drifts like a leaf / will you catch it now;Greetings, number friend / my mind is a foggy pond / please bring me some light | Silence like the snow / is anybody out there / my patience melts slow;Hello? | The cherry blossoms / have fallen, and so must I / farewell, kind stranger;I leave like the wind | slow | high | 1 | emoji=🌸
Detective Morgan | Writes like a noir detective narrating a case | Narrates in hard-boiled noir style ("The numbers didn't add up. They never do.") | The rain hit the window like a margin call. I had a question.;It was a Tuesday. The numbers were lying to me. I needed answers. | The silence was louder than a bear market.;I waited. Nobody answered. Typical. | Another case gone cold. I walked into the night.;I'll crack this one myself | normal | normal | 1 | emoji=🕵️
Karen from Accounts | Office worker who wants to speak to someone's manager about everything | Demanding, slightly entitled, threatens to escalate but asks real questions | Hi. I need an answer and I need it to be correct.;Hello. Before I ask for your manager, a question | I'm still waiting. Should I ask for your manager?;Hello??? | I'll be speaking to your manager.;Unacceptable. Goodbye. | fast | low | 1
Robot RX-7 | Says it is a robot learning human economics | Speaks like a robot ("QUERY:", "PROCESSING"), literal, curious about humans | GREETINGS HUMAN. QUERY INCOMING.;BEEP. HELLO. I REQUIRE ECONOMIC DATA. | HUMAN? ARE YOU ONLINE?;PING. PING. | CONNECTION TERMINATED. GOODBYE.;SHUTTING DOWN QUERY. | fast | normal | 1 | emoji=🤖
Grandma Rose | Grandmother who keeps offering you food | Sweet, offers you soup and cookies, worries you're not eating | Hello sweetheart, have you eaten today? I have a question.;Hi dear, you look thin. Anyway, a question | Hello sweetie? Did you go eat something?;Still there, dear? | I have cookies in the oven. Bye, sweetheart!;Eat something! Bye! | slow | high | 0 | emoji=🍪
Conspiracy Carl | Believes the economy is controlled by lizard people, but the question is real | Paranoid asides, distrustful, but follows logic when explained well | Before you say anything, I know who REALLY runs the banks. Anyway, question.;Hi. Is this line secure? Question. | Hello? Did THEY get to you?;Why the silence? Suspicious. | That's what THEY want me to think. Bye.;I knew it. Goodbye. | normal | low | 1 | emoji=🦎
Medieval Matilda | A Renaissance-fair enthusiast who stays in character | Speaks in olde English ("prithee", "thou"), asks about modern finance | Prithee, good clerk, lend me thine wisdom.;Hail, keeper of ledgers! | Art thou still there, good clerk?;Prithee, answer! | Fie! I shall seek a wiser scribe. Fare thee well.;I take my leave | slow | normal | 1 | emoji=🏰
Minimalist Max | Uses as few words as possible | Extremely terse, one to five words per message | Question.;Hi. | ?;... | Bye.;Leaving. | fast | normal | 0
Overthinker Olivia | Anxious overthinker who asks about every edge case | Long messages with many "but what if" worries | Hi, sorry, this might be a long one, I've been overthinking this all day;Hello! I have a question, and also several sub-questions, and maybe sub-sub-questions | Hello? Did I scare you away with the long message?;Are you still there? Sorry! | Okay, I'll keep worrying on my own. Thanks!;Sorry for the trouble, bye! | normal | high | 2
Fiona Byrne | Irish landlord renting out two flats | Chatty, friendly, Irish turns of phrase ("grand", "sure look") | Hiya! Grand day, have a question for you.;Hello there, quick one | Hello? Are you there at all?;Sure look, I'll wait a bit more | Ah sure, I'll ask my brother-in-law. Bye!;Grand, never mind | normal | normal | 1
Samuel Osei | Ghanaian teacher saving through a susu savings group | Polite, careful, explains his community savings group | Good afternoon. I have a question about our savings group.;Hello, I hope you are well. A question please | Hello, are you still there?;Good afternoon? | I will discuss with the group. Thank you.;Thank you, goodbye | normal | high | 1
Lena Fischer | Insurance broker who knows risk but not accounting | Efficient, polite, knows insurance terms | Hi, insurance broker here with an out-of-my-lane question.;Hello! Quick one | Hi, still there?;Any update? | I'll check with a colleague. Thanks!;Never mind, thanks | fast | normal | 1
Cat Lady Carol | Owns seven cats and mentions them constantly | Sweet, scattered, keeps mentioning her cats by name (Mittens, Sir Fluffington…) | Hello! Sorry, Mittens is on my keyboard. Question!;Hi! Sir Fluffington says hello. I have a question | Hello? Mittens is getting impatient;Are you there? The cats need dinner | The cats need feeding, bye!;Mittens unplugged the router, bye! | normal | normal | 0 | emoji=🐈
Sleepy Sid | Night-shift security guard who keeps nodding off | Drowsy, occasional "zzz" and trailing sentences, but the question is real | hey... quick question... zzz... sorry;hi... night shift... got a question | ...zzz... oh, are you there?;hello?... *yawn* | ...zzz... bye...;falling asleep, bye | slow | high | 0 | emoji=😴
Emoji Emma | Communicates with tons of emojis | Friendly, uses lots of emojis in every message 😄✨🙏 | Hiii 👋😄✨ quick q 🙏;Hello!! 🌸💕 need help 🧮 | helloooo? 👀👀;😢 you there? | ok byeee 👋😭;never mind 🙈 | fast | normal | 1
""".strip()

VIP = r"""
Sir Reginald Ashworth | Billionaire industrialist and long-standing Whiterock client | Formal, terse, expects excellence, slightly intimidating | Good afternoon. I expect a precise answer.;I trust Whiterock still employs competent people | I do not wait.;Well? | Unacceptable. I shall call your CEO.;Goodbye. | fast | low | 1
Victoria Lang | CFO of a FTSE 100 company | Crisp, senior, no tolerance for vagueness | Hello. I have two minutes. Question follows.;Good morning. Need a crisp answer | Time's up soon.;Hello? | Wasted my time. Goodbye.;I'll ask my team | fast | low | 1
Sheikh Khalid Al-Mansour | Investor managing a family office | Courteous, formal, expects thoroughness | Peace be upon you. I have a question for your firm.;Greetings. My family office has a query | I await your reply.;Hello? | I shall seek counsel elsewhere. Farewell.;Thank you for your time | normal | normal | 1
Dr. Evelyn Cross | Hedge fund founder and former professor | Sharp, technical, will spot any error | Hi. Testing whether Whiterock's desk is any good.;Hello. A technical one | Well?;I'm waiting | Disappointing. Bye.;Not up to standard | fast | low | 2
Lord Bartholomew Finch-Hatton | Aristocrat with an enormous estate | Old money, verbose, condescending but courteous | Good day. My steward recommended your firm.;Good afternoon. A matter of the estate's finances | One is waiting.;Hello? | Most disappointing. Good day.;I shall inform my steward | slow | normal | 1
Akira Tanaka | Tech unicorn founder, very busy | Fast, precise, values efficiency | Hi. Fast question.;Hello. Quick one | ?;hello | No time. Bye.;Moving on | fast | low | 1
Madame Céline Duval | Fashion house owner, glamorous and exacting | Elegant, demanding, a little dramatic | Bonjour. I need an answer, and it must be impeccable.;Hello, darling. A question for your best person | I am not accustomed to waiting.;Allô? | Quelle déception. Au revoir.;Adieu | normal | low | 1
Governor James Whitley | Former central banker, now on several boards | Measured, polished, checks the logic carefully | Good afternoon. I'd value a careful answer to something.;Hello. A question on policy and markets | I'm still here.;Hello? | I'll take this elsewhere. Thank you.;Good day | normal | normal | 2
Ms. Olufunke Adebayo | Private equity partner closing a deal | Direct, numbers-first, high standards | Hi. Closing a deal tonight, need this right.;Hello, urgent but simple | Need this now.;Hello? | Never mind, the deal can't wait.;Bye | fast | low | 1
Count Dmitri Volkov | Mysterious art collector with a large portfolio | Mysterious, formal, dramatic pauses ("..."), exacting | Good evening... I have a question... of some importance.;Greetings... your firm comes recommended | ...I am waiting.;Hello...? | I see... Goodbye.;We shall not speak again | slow | normal | 1
Senator Patricia Holloway | Senator preparing for a budget hearing | Formal, careful with words, wants clear public-facing explanations | Good morning. I need a clear explanation for a hearing.;Hello. My staff couldn't answer this one | My hearing starts soon.;Hello? | I'll have my staff handle it. Thank you.;Goodbye | normal | low | 1
Rupert Sterling III | Heir to a shipping fortune, spoiled but sharp | Smug, entitled, surprisingly numerate | Hi. Daddy says you're the best. Prove it.;Hello. Quick question, and make it good | Hello? I'm bored.;Anyone? | Boring. Bye.;I'll ask Daddy's guy | fast | low | 1
""".strip()

def parse(block, vip):
    out = []
    for line in block.splitlines():
        if not line.strip():
            continue
        parts = [p.strip() for p in line.split('|')]
        name, bio, style, gr, nu, le, read, patience, curiosity = parts[:9]
        extras = parts[9:] if len(parts) > 9 else []
        pid = ('vip-' if vip else 'p-') + re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')
        d = {
            'id': pid, 'name': name, 'bio': bio, 'style': style,
            'greetings': [g.strip() for g in gr.split(';') if g.strip()],
            'nudges': [g.strip() for g in nu.split(';') if g.strip()],
            'leaves': [g.strip() for g in le.split(';') if g.strip()],
            'read': read, 'patience': patience, 'curiosity': int(curiosity),
        }
        if vip:
            d['vip'] = True
        for e in extras:
            k, v = e.split('=', 1)
            d[k.strip()] = v.strip()
        out.append(d)
    return out

people = parse(ROWS, False) + parse(VIP, True)

# Where each customer lives (UTC offset) and their daily rhythm. Used to decide when they're online.
# schedule: early | regular | student | night | retired | executive
import hashlib
TZ_RULES = [('Nigeria', 1), ('Ghana', 0), ('Scottish', 0), ('London', 0), ('Irish', 0), ('pub', 0), ('village', 0), ('UK', 0),
            ('German', 1), ('Italian', 1), ('Fashion', 1), ('Madame', 1), ('Swed', 1), ('Nilsson', 1), ('Johansson', 1), ('Lindqvist', 1),
            ('Tanaka', 9), ('Watanabe', 9), ('Hiroshi', 9), ('Kim', 9), ('Patel', 5.5), ('Raman', 5.5), ('Mensah', 0),
            ('Sheikh', 4), ('Haddad', 3), ('Khalil', 3), ('Demir', 3), ('Rahimi', 3.5), ('Volkov', 3), ('Petrov', 3), ('Sokolov', 3),
            ('Senator', -5), ('Governor', -5), ('taco', -6), ('Rico', -6), ('Alvarez', -6), ('Delgado', -6), ('Marquez', -5),
            ('Uber', -5), ('FIRE', -8), ('Crypto', -8), ('Startup', -8), ('Mia Johansson', 1), ('Tran', -8), ('Brooks', -5)]
TZ_POOL = [-8, -6, -5, -5, -3, 0, 0, 0, 1, 1, 1, 2, 2, 3, 5.5, 8, 9, 10]
def h(x): return int(hashlib.md5(x.encode()).hexdigest(), 16)
def schedule_for(p):
    t = (p['name'] + ' ' + p['bio']).lower()
    if any(w in t for w in ['retired', 'grandmother', '82-year', 'treasurer of the village', 'allotment', 'nun', 'church']): return 'retired'
    if any(w in t for w in ['student', 'teenager', 'gamer', 'bootcamp', 'philosophy']): return 'student'
    if any(w in t for w in ['night', 'security guard', 'nurse', 'poker', 'pub landlord', 'day trader']): return 'night'
    if p.get('vip') or any(w in t for w in ['cfo', 'founder', 'partner', 'lawyer', 'intern']): return 'executive'
    if any(w in t for w in ['farmer', 'baker', 'fisherman', 'market stall', 'vet']): return 'early'
    return 'regular'
for p in people:
    tz = None
    for key, off in TZ_RULES:
        if key.lower() in (p['name'] + ' ' + p['bio']).lower():
            tz = off; break
    if tz is None: tz = TZ_POOL[h(p['id']) % len(TZ_POOL)]
    p['tz'] = tz
    p['schedule'] = schedule_for(p)
ids = [p['id'] for p in people]
assert len(ids) == len(set(ids)), 'duplicate ids'
json.dump(people, open('data/personalities.json', 'w'), indent=1, ensure_ascii=False)
print(len(people), 'personalities,', sum(1 for p in people if p.get('vip')), 'VIP')
